<?php defined('BMEI_WWW') or die();


const PATH_INTERNAL = 1;
const PATH_EXTERNAL = 2;

const NEWS_ANNOUNCEMENT = 1;
const NEWS_RESEARCH = 2;
const NEWS_PROJECT = 3;
const NEWS_JOBS = 4;

const STAFF_LECTURER = 1;
const STAFF_RESEARCHER = 2;
const STAFF_OFFICER = 3;

const DOCUMENT_MODE_DOCUMENT = 1;
const DOCUMENT_MODE_REPORT = 2;

const DOCUMENT_ANNOUNCEMENT = 1;
const DOCUMENT_INSTITUTE_COMMAND = 2;
const DOCUMENT_UNIVERSITY_COMMAND = 3;

const REPORT_DIRECTOR_BOARD = 64;
const REPORT_MANAGER_BOARD = 65;
const REPORT_MANAGER = 66;
